# Generated by Django 4.2.2 on 2023-07-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('talon_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество всех талонов очереди')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqs', to='branch.branch', verbose_name='Филиал')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqs', to='base.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очереди',
            },
        ),
    ]
