# Generated by Django 4.2.2 on 2023-07-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
            options={
                'verbose_name': 'Не рабочий день',
                'verbose_name_plural': 'Не рабочие дни',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='документ', max_length=100, verbose_name='Название')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('required', models.BooleanField(default=True, verbose_name='Обязателен')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=30, verbose_name='Язык')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=50, unique=True)),
                ('pin', models.CharField(max_length=50)),
                ('organization', models.CharField(default='RSK Bank', max_length=100)),
                ('auth_token', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('average_time', models.BigIntegerField(blank=True, default=3, verbose_name='Среднее время обслуживания в минутах')),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('auto_transport', models.BooleanField(default=False, verbose_name='Авто перенос талона')),
                ('documents', models.ManyToManyField(related_name='service', to='base.document', verbose_name='Документы')),
                ('lang_name', models.ManyToManyField(related_name='service', to='base.languagename', verbose_name='Название для разных языков')),
                ('service_to_auto_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='base.service', verbose_name='Услуга для переноса')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='lang_name',
            field=models.ManyToManyField(related_name='documents', to='base.languagename', verbose_name='Название для разных языков'),
        ),
    ]
