version: "3.9"
applications:
  services:

    redis:
      image: redis
      restart: always
      env_file:
        - ./.env
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
        - ./server/redis:/opt/redis
    db:
      restart: always
      image: postgres:13.4
      container_name: db
      env_file:
        - ./.env
      volumes:
        - ./server/database/postgres_data:/var/lib/postgresql/

    pgbouncer:
      image: pgbouncer/pgbouncer
      container_name: pgbouncer
      depends_on:
        - db
      ports:
        - "6433:6432"
      env_file:
        - ./.env
      volumes:
        - ./server/database/pgbouncer_config:/etc/pgbouncer
      user: "1000:1000"
      command: sh -c "source /etc/pgbouncer/pgbouncer.env && /etc/pgbouncer/setup_pgbouncer.sh"
      
    database_admin:
      image: adminer
      restart: always
      ports:
        - 8081:8080
      env_file:
        - ./.env
      depends_on:
        - db

    rsk_django:
      build: ./server/src
      command: >
        bash -c "./manage.py collectstatic --noinput &&
          ./manage.py migrate && 
          gunicorn -b 0.0.0.0:8000 config.wsgi:application"
      ports:
        - "8000:8000"
      env_file:
        - ./.env
      volumes:
        - ./server/src:/app
        - app_data:/db 
        - app_data:/app/static
        - app_data:/app/media
      depends_on:
        - pgbouncer 
        - redis   

    celery:
      build: ./server/src
      command: >
        sh -c "celery -A config worker -l info"
      env_file:
        - ./.env
      volumes:
        - ./server/src:/app
        - app_data:/db 
      depends_on:
        - rsk_django

    nginx:
      build:
        dockerfile: ./Dockerfile
        context: ./docker/nginx/
      container_name: nginx
      image: nginx
      volumes:
        -
        - app_data:/root/static
        - app_data:/root/media
      depends_on:
        - rsk_django
      ports:
        - "${NGINX_EXTERNAL_PORT}:80"
    
    flower:
      image: mher/flower
      command: celery --broker=redis://redis:6379 flower --port=5556
      ports:
        - 5556:5556
      depends_on:
        - redis

volumes:
  app_data:
  pgbouncer_data: