# Generated by Django 4.2.2 on 2023-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
