# Generated by Django 4.2.2 on 2023-07-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_customtoken_expiration_date_delete_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtoken',
            name='expiration_date',
        ),
    ]
