# Generated by Django 4.2.2 on 2023-07-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='ad_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('work_time_start', models.TimeField(verbose_name='Начало рабочего дня')),
                ('work_time_end', models.TimeField(verbose_name='Конец рабочего дня')),
                ('lang_name', models.ManyToManyField(related_name='branch', to='base.languagename', verbose_name='Название для разных языков')),
                ('service', models.ManyToManyField(related_name='branch', to='base.service', verbose_name='Услуги')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='base.terminal', verbose_name='Терминал')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='RunningString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер окна')),
                ('branch', models.ForeignKey(help_text='Выберите филиал', on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='branch.branch', verbose_name='Филиал')),
            ],
        ),
    ]
