# Generated by Django 4.2.2 on 2023-07-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('branch', '0001_initial'),
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Токен')),
                ('status', models.CharField(default='waiting', max_length=100, verbose_name='Статус')),
                ('client_type', models.CharField(max_length=100, verbose_name='Тип клиента')),
                ('client_comment', models.CharField(blank=True, max_length=100, verbose_name='Комментарий клиента')),
                ('employee_comment', models.CharField(blank=True, max_length=200, verbose_name='Коментарий сотрудника')),
                ('is_pensioner', models.BooleanField(default=False, verbose_name='Пенсионер')),
                ('service_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало обслуживания')),
                ('service_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец обслуживания')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Примерное время приема')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talon', to='branch.branch', verbose_name='Филиал')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talon', to='client.client', verbose_name='Клиент')),
                ('operators', models.ManyToManyField(blank=True, related_name='talon', to=settings.AUTH_USER_MODEL, verbose_name='Операторы')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talon', to='eqs.eqs', verbose_name='Очередь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talon', to='base.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='branch.branch')),
                ('talon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talons', to='talon.talon')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='branch.window')),
            ],
        ),
    ]
