# Generated by Django 4.2.3 on 2023-07-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='is_appointed',
            field=models.BooleanField(default=False, verbose_name='Назначен'),
        ),
    ]
