# Generated by Django 4.2.2 on 2023-07-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Эл. Почта')),
                ('username', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('operator', 'operator'), ('registrator', 'registrator')], max_length=100)),
                ('shift', models.CharField(blank=True, max_length=100, verbose_name='Перерыв')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Коментарий')),
                ('status', models.CharField(default='active', max_length=255, verbose_name='Статус')),
                ('max_transport', models.PositiveIntegerField(default=0, verbose_name='Ограничение переноса талонов')),
                ('auto_call', models.BooleanField(default=False, verbose_name='Авто вызов талона')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='branch.branch', verbose_name='Филиал')),
                ('service', models.ManyToManyField(blank=True, related_name='employee', to='base.service', verbose_name='Услуги')),
                ('window', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='branch.window', verbose_name='Окно')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
