TALON_STATUS_COMPLETED = 'completed'
TALON_STATUS_CANCELED = 'canceled'
TALON_STATUS_WAITING = 'waiting'
TALON_STATUS_INSERVICE = 'in service'

EMPLOYEE_STATUS_ACTIVE = 'active'
EMPLOYEE_STATUS_INACTIVE = 'inactive'
